# Generated by Django 6.0.6 on 2026-07-15 09:48

import accounts.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. CYB, CID', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hierarchy_level', models.PositiveSmallIntegerField(help_text='Lower number = more senior. 1 = DGP, ... , 10 = Constable', validators=[accounts.validators.validate_hierarchy_level])),
            ],
            options={
                'db_table': 'rank',
                'ordering': ['hierarchy_level'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'police_station',
                'ordering': ['district', 'name'],
                'indexes': [models.Index(fields=['district'], name='police_stat_distric_f68be4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_number', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Badge number can only contain letters, numbers, and hyphens.', regex='^[A-Za-z0-9\\-]+$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian phone number (10 digits, optionally prefixed with +91).', regex='^(\\+91)?[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='accounts.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='accounts.policestation')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='accounts.rank')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='accounts.role')),
            ],
            options={
                'db_table': 'officer',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['badge_number'], name='officer_badge_n_1ec310_idx'), models.Index(fields=['police_station'], name='officer_police__71f488_idx')],
            },
        ),
    ]
