# Generated by Django 6.0.6 on 2026-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='jurisdiction_district',
            field=models.CharField(blank=True, help_text='Only set for SP/DIG roles — the district they oversee. Leave blank for Constable/Station Officer (use police_station instead) and DGP/SCRB Analyst (state-wide, no district restriction).', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('CONSTABLE', 'Constable'), ('STATION_OFFICER', 'Station Officer'), ('SP_DIG', 'SP / DIG'), ('DGP', 'DGP'), ('SCRB_ANALYST', 'SCRB Analyst')], max_length=20, unique=True),
        ),
    ]
