# Generated by Django 6.0.6 on 2026-07-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260716_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='department',
        ),
        migrations.AddField(
            model_name='policestation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='police_stations', to='accounts.department'),
        ),
    ]
