# Generated by Django 6.0.6 on 2026-07-15 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike / Motorcycle'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('AUTO', 'Auto Rickshaw'), ('OTHER', 'Other')], default='CAR', max_length=10)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('is_stolen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SEIZED', 'Seized'), ('IMPOUNDED', 'Impounded'), ('RECOVERED', 'Recovered')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle',
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['registration_number'], name='vehicle_registr_8a1aa4_idx'), models.Index(fields=['is_stolen'], name='vehicle_is_stol_214bef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('LAND', 'Land'), ('BUILDING', 'Building'), ('JEWELRY', 'Jewelry'), ('ELECTRONICS', 'Electronics'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('REPORTED_STOLEN', 'Reported Stolen'), ('RECOVERED', 'Recovered'), ('SEIZED', 'Seized'), ('RELEASED', 'Released')], default='REPORTED_STOLEN', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='investigations.investigationcase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='persons.person')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'property',
                'indexes': [models.Index(fields=['status'], name='property_status_b6c25e_idx'), models.Index(fields=['case'], name='property_case_id_22f5f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ownership_type', models.CharField(choices=[('CURRENT', 'Current'), ('PREVIOUS', 'Previous')], default='CURRENT', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_ownerships', to='persons.person')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='assets.vehicle')),
            ],
            options={
                'db_table': 'vehicle_ownership',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_own_vehicle_448118_idx'), models.Index(fields=['owner'], name='vehicle_own_owner_i_a23309_idx')],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weapon_type', models.CharField(choices=[('FIREARM', 'Firearm'), ('KNIFE', 'Knife'), ('EXPLOSIVE', 'Explosive'), ('OTHER', 'Other')], max_length=10)),
                ('license_number', models.CharField(blank=True, help_text='Blank if unlicensed/illegal', max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('LICENSED', 'Licensed'), ('ILLEGAL', 'Illegal'), ('SEIZED', 'Seized'), ('RELEASED', 'Released')], default='ILLEGAL', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='investigations.investigationcase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='persons.person')),
            ],
            options={
                'db_table': 'weapon',
                'indexes': [models.Index(fields=['status'], name='weapon_status_76a0af_idx'), models.Index(fields=['case'], name='weapon_case_id_cd8aa5_idx')],
            },
        ),
    ]
