# Generated by Django 6.0.6 on 2026-07-15 10:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('aadhaar_number', models.CharField(blank=True, help_text='12-digit Aadhaar ID, optional/unknown for many records', max_length=12, null=True, unique=True)),
                ('father_or_guardian_name', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='person_last_na_85a3c4_idx'), models.Index(fields=['aadhaar_number'], name='person_aadhaar_e0efc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('WORK', 'Work'), ('OTHER', 'Other')], default='PERSONAL', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='persons.person')),
            ],
            options={
                'db_table': 'email',
                'indexes': [models.Index(fields=['email'], name='email_email_076f89_idx'), models.Index(fields=['person'], name='email_person__61e82f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current'), ('WORK', 'Work'), ('OTHER', 'Other')], default='CURRENT', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='persons.person')),
            ],
            options={
                'db_table': 'address',
                'indexes': [models.Index(fields=['person'], name='address_person__b20795_idx'), models.Index(fields=['district'], name='address_distric_188ba1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonCaseRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('VICTIM', 'Victim'), ('SUSPECT', 'Suspect'), ('WITNESS', 'Witness'), ('ACCUSED', 'Accused'), ('COMPLAINANT', 'Complainant')], max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_roles_added', to='accounts.officer')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='investigations.investigationcase')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_roles', to='persons.person')),
            ],
            options={
                'db_table': 'person_case_role',
                'indexes': [models.Index(fields=['case'], name='person_case_case_id_db1edf_idx'), models.Index(fields=['role'], name='person_case_role_b95306_idx')],
                'unique_together': {('person', 'case', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian phone number (10 digits, optionally prefixed with +91).', regex='^(\\+91)?[6-9]\\d{9}$')])),
                ('phone_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], default='MOBILE', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='persons.person')),
            ],
            options={
                'db_table': 'phone',
                'indexes': [models.Index(fields=['phone_number'], name='phone_phone_n_1ff78f_idx'), models.Index(fields=['person'], name='phone_person__d0f21e_idx')],
            },
        ),
    ]
