# Generated by Django 6.0.6 on 2026-07-15 10:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Theft, Cyber Fraud, Assault', max_length=150, unique=True)),
                ('code_type', models.CharField(choices=[('BNS', 'Bharatiya Nyaya Sanhita'), ('IPC', 'Indian Penal Code (pre-2024, legacy records)'), ('IT_ACT', 'Information Technology Act'), ('OTHER', 'Other / Special Law')], default='BNS', max_length=10)),
                ('section_code', models.CharField(help_text='e.g. BNS Section 303', max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('HEINOUS', 'Heinous')], default='MODERATE', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crime_category',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['section_code'], name='crime_categ_section_f4609c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_of_occurrence', models.DateField()),
                ('time_of_occurrence', models.TimeField(blank=True, null=True)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CHARGESHEET_FILED', 'Chargesheet Filed'), ('CLOSED', 'Closed')], default='REPORTED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crimes', to='accounts.policestation')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crimes_reported', to='accounts.officer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crimes', to='crimes.crimecategory')),
            ],
            options={
                'db_table': 'crime',
                'ordering': ['-date_of_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fir_number', models.CharField(help_text='e.g. 0123/2026 — station code + sequence + year', max_length=50, unique=True)),
                ('complainant_name', models.CharField(max_length=150)),
                ('complainant_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian phone number (10 digits, optionally prefixed with +91).', regex='^(\\+91)?[6-9]\\d{9}$')])),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CHARGESHEET_FILED', 'Chargesheet Filed'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=25)),
                ('summary', models.TextField(help_text='Brief narrative of the complaint')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firs', to='accounts.policestation')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firs_registered', to='accounts.officer')),
            ],
            options={
                'db_table': 'fir',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='FIRCrime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary_offense', models.BooleanField(default=False, help_text='Marks the main/most severe offense in this FIR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fir_crimes', to='crimes.crime')),
                ('fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fir_crimes', to='crimes.fir')),
            ],
            options={
                'db_table': 'fir_crime',
            },
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['police_station'], name='crime_police__7a4920_idx'),
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['status'], name='crime_status_4dbf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['date_of_occurrence'], name='crime_date_of_530543_idx'),
        ),
        migrations.AddIndex(
            model_name='fir',
            index=models.Index(fields=['fir_number'], name='fir_fir_num_f89f88_idx'),
        ),
        migrations.AddIndex(
            model_name='fir',
            index=models.Index(fields=['police_station'], name='fir_police__de0e79_idx'),
        ),
        migrations.AddIndex(
            model_name='fir',
            index=models.Index(fields=['status'], name='fir_status_7ba367_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fircrime',
            unique_together={('fir', 'crime')},
        ),
    ]
