# Generated by Django 6.0.6 on 2026-07-15 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(help_text='e.g. CR-2026-00123', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CHARGESHEET_FILED', 'Chargesheet Filed'), ('IN_COURT', 'In Court'), ('CLOSED', 'Closed'), ('DROPPED', 'Dropped')], default='OPEN', max_length=25)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fir', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_case', to='crimes.fir')),
                ('lead_officer', models.ForeignKey(help_text='Current officer in charge of the case', on_delete=django.db.models.deletion.PROTECT, related_name='cases_leading', to='accounts.officer')),
            ],
            options={
                'verbose_name': 'Investigation Case',
                'verbose_name_plural': 'Investigation Cases',
                'db_table': 'investigation_case',
                'ordering': ['-opened_date'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations_handled', to='accounts.officer')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='investigations.investigationcase')),
            ],
            options={
                'db_table': 'investigation',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Chargesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_referred', models.CharField(blank=True, help_text='Temporary — court name as text', max_length=200)),
                ('filing_date', models.DateField()),
                ('sections_summary', models.TextField(help_text='Summary of sections/charges applied')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FILED', 'Filed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargesheets_filed', to='accounts.officer')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargesheets', to='investigations.investigationcase')),
            ],
            options={
                'db_table': 'chargesheet',
                'ordering': ['-filing_date'],
            },
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrested_person_name', models.CharField(max_length=150)),
                ('arrested_person_details', models.TextField(blank=True, help_text='Temporary free-text: age, address, ID details, etc.')),
                ('arrest_date', models.DateTimeField()),
                ('arrest_location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arresting_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrests_made', to='accounts.officer')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrests', to='investigations.investigationcase')),
            ],
            options={
                'db_table': 'arrest',
                'ordering': ['-arrest_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('step_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='investigations.investigation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps_performed', to='accounts.officer')),
            ],
            options={
                'db_table': 'investigation_step',
                'ordering': ['step_date'],
            },
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_case_number', models.CharField(max_length=50, unique=True)),
                ('court_name', models.CharField(blank=True, help_text='Temporary — court name as text', max_length=200)),
                ('filing_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('ADJOURNED', 'Adjourned'), ('JUDGMENT_RESERVED', 'Judgment Reserved'), ('DISPOSED', 'Disposed'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted')], default='PENDING', max_length=20)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('verdict', models.TextField(blank=True)),
                ('verdict_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chargesheet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='court_case', to='investigations.chargesheet')),
            ],
            options={
                'verbose_name': 'Court Case',
                'verbose_name_plural': 'Court Cases',
                'db_table': 'court_case',
                'ordering': ['-filing_date'],
                'indexes': [models.Index(fields=['court_case_number'], name='court_case_court_c_a456b1_idx'), models.Index(fields=['status'], name='court_case_status_c6dec3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='investigationcase',
            index=models.Index(fields=['case_number'], name='investigati_case_nu_b3520a_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationcase',
            index=models.Index(fields=['status'], name='investigati_status_05f7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['case'], name='investigati_case_id_713b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['officer'], name='investigati_officer_0c55ec_idx'),
        ),
        migrations.AddIndex(
            model_name='chargesheet',
            index=models.Index(fields=['case'], name='chargesheet_case_id_822846_idx'),
        ),
        migrations.AddIndex(
            model_name='chargesheet',
            index=models.Index(fields=['status'], name='chargesheet_status_20ec5c_idx'),
        ),
        migrations.AddIndex(
            model_name='arrest',
            index=models.Index(fields=['case'], name='arrest_case_id_4d8c64_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationstep',
            index=models.Index(fields=['investigation'], name='investigati_investi_88b461_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationstep',
            index=models.Index(fields=['step_date'], name='investigati_step_da_7b438b_idx'),
        ),
    ]
