# Generated by Django 6.0.6 on 2026-07-15 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_officer_jurisdiction_district_alter_role_name'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Auto-generated or officer-set title', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, help_text='Optional — link this chat to a specific case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='investigations.investigationcase')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.officer')),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], max_length=5)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='LangChain execution trace: tool used, generated SQL/Cypher, source, reasoning', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('QUERY', 'AI Query'), ('LOGIN', 'Login'), ('DATA_ACCESS', 'Data Access'), ('EXPORT', 'Export'), ('OTHER', 'Other')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.officer')),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='assistant.conversation')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('CRIME_SUMMARY', 'Crime Summary'), ('CASE_REPORT', 'Case Report'), ('ANALYTICS', 'Analytics'), ('CUSTOM', 'Custom')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('content_summary', models.TextField(blank=True)),
                ('file_reference', models.CharField(blank=True, help_text='Temporary — path/URL as text', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='investigations.investigationcase')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_generated', to='accounts.officer')),
            ],
            options={
                'db_table': 'generated_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('CRIME_HOTSPOT', 'Crime Hotspot'), ('CRIME_TREND', 'Crime Trend'), ('RISK_SCORE', 'Risk Score'), ('OTHER', 'Other')], max_length=20)),
                ('input_parameters', models.JSONField(help_text='Parameters passed to the model')),
                ('output_result', models.JSONField(help_text='Model output — structure varies by prediction_type')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='investigations.investigationcase')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions_requested', to='accounts.officer')),
            ],
            options={
                'verbose_name_plural': 'Prediction History',
                'db_table': 'prediction_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['officer'], name='conversatio_officer_cd4e98_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['case'], name='conversatio_case_id_17fc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation'], name='chat_messag_convers_1d5c10_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_messag_created_b6b51c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['officer'], name='audit_log_officer_5c77b8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='audit_log_action__ff81b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_type'], name='generated_r_report__99b5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['case'], name='generated_r_case_id_f76763_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['prediction_type'], name='prediction__predict_a2bea9_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['created_at'], name='prediction__created_0b3269_idx'),
        ),
    ]
